### PR TITLE
Fix #2375  missing stdint.h for py2.7 vc9

### LINKED ISSUE #2375: Parfors compile error due to stdint.h missing on Windows Python2.7 VC++9.0
Compilation parfor C files is failing on windows python2.7 due to missing stdint.h

```
c:\users\buildbot\hpa-ci\buildbot-slave\var-64\pr_numba-py2_7-np1_10-w64\build\numba\npyufunc\gufunc_scheduler.h(4) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
```

### PR DESCRIPTION
**Pull request by sklam**
Base on #2374 
Closes #2375

### CODE REVIEW

File: numba/npyufunc/gufunc_scheduler.h [hunk 1]
```diff
@@ -1,8 +1,26 @@
 #ifndef GUFUNC_SCHEDULER
 #define GUFUNC_SCHEDULER
 
-#include <stdint.h>
-#if __SIZEOF_POINTER__ == 8
+/* define int64_t and uint64_t for VC9 */
```
Comment (seibert) [inline numba/npyufunc/gufunc_scheduler.h]: this comment is slightly inaccurate.  The #ifdef will branch will be taken for all versions of Visual Studio, not just VS2008
