### PR TITLE
Fix #6444: pruner issues with reference stealing functions

### LINKED ISSUE #6444: 0.52.0rc2 regression: invalid array data if used after print
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Array data looks invalid if used after a print. Looks like a refcount issue:
```python
import numba
import numpy as np

@numba.njit
def f():
    A = np.ones(3)
    print(A)
    return A[0]

print(f())
```
```
[1. 1. 1.]
-9.868309920863368e+148
```

### PR DESCRIPTION
**Pull request by sklam**
Fixes https://github.com/numba/numba/issues/6444

### CODE REVIEW

File: numba/core/runtime/_nrt_python.c [hunk 1]
```diff
@@ -286,7 +286,7 @@ PyObject* try_to_return_parent(arystruct_t *arystruct, int ndim,
 }
 
 NUMBA_EXPORT_FUNC(PyObject *)
-NRT_adapt_ndarray_to_python(arystruct_t* arystruct, int ndim,
+NRT_adapt_ndarray_to_python_acqref(arystruct_t* arystruct, int ndim,
```
Comment (stuartarchibald) [inline numba/core/runtime/_nrt_python.c:289]: Whilst highly unlikely, any chance anyone else is using this? I did a quick scan of github and nothing jumped out.

Comment (stuartarchibald) [inline numba/core/runtime/_nrt_python.c:289]: Also suggest adding a docstring, perhaps ref this PR?

**Review by stuartarchibald — COMMENTED** [review]
Thanks for the patch, think this will fix the issue. Is there a test that can be added to demonstrate?

File: numba/core/runtime/_nrt_python.c (hunk 1 above)
Comment (sklam) [reply numba/core/runtime/_nrt_python.c:289]: It has to be very unusual for anyone to be using this. Also external code are advised to use: https://numba.readthedocs.io/en/stable/developer/numba-runtime.html?highlight=runtime#using-the-nrt-from-c-code which does not expose this function.

File: docs/source/developer/numba-runtime.rst [hunk 2]
```diff
@@ -48,17 +48,34 @@ Optimizations
...
-operations.
+on an optimization pass that remove the redundant reference count operations.
 
-The optimization pass runs on block level to avoid control flow analysis.
+A new optimization pass is implemented in version 0.52.0 to remove reference
+count operations that falls into the following four categories of control-flow
+structure---per basic-block, diamond, fanout, fanout+raise. See documentation
+of :envvar:`NUMBA_LLVM_REFPRUNE_FLAGS` for their descriptions.
+
+The old optimization pass runs on block level to avoid control flow analysis.
```
[the remark this answers is not in the document]
Comment (sklam) [reply docs/source/developer/numba-runtime.rst:58]: done

File: numba/core/runtime/_nrt_python.c (hunk 1 above)
Comment (sklam) [reply numba/core/runtime/_nrt_python.c:294]: done

**Comment by stuartarchibald** [comment]
Close/reopen was because Azure got irretrievably stuck on due to a deprovisioning request.

File: numba/core/runtime/_nrt_python.c (hunk 1 above)
Comment (stuartarchibald) [reply numba/core/runtime/_nrt_python.c:294]: Agree about it being unusual, I think given docs do not expose this it can be considered internal only and changed.

File: numba/core/runtime/_nrt_python.c [hunk 3]
```diff
@@ -285,8 +285,13 @@ PyObject* try_to_return_parent(arystruct_t *arystruct, int ndim,
     return NULL;
 }
 
+/**
+ * This function was renamed in 0.52.0 to specify that it acquires references.
+ * It used to steal the reference of the arystruct.
+ * Refers to https://github.com/numba/numba/pull/6446
```
Comment (stuartarchibald) [inline numba/core/runtime/_nrt_python.c:291]:
```suggestion
 * Refer to https://github.com/numba/numba/pull/6446
```

File: docs/source/developer/numba-runtime.rst [hunk 4]
```diff
@@ -48,21 +48,39 @@ Optimizations
...
+Quirks of legacy optimization pass
+----------------------------------
 
-Since the `refcount optimization pass <nrt-refct-opt-pass_>`_ requires LLVM
-function optimization pass, the pass works on the LLVM IR as text.  The
-optimized IR is then materialized again as a new LLVM in-memory bitcode object.
+Since the pre-0.52.0 `refcount optimization pass <nrt-refct-opt-pass_>`_
+requires LLVM function optimization pass, the pass works on the LLVM IR as
+text. The optimized IR is then materialized again as a new LLVM in-memory
+bitcode object.
```
Comment (stuartarchibald) [inline docs/source/developer/numba-runtime.rst:83]: I'm not sure what this is trying to convey? Is it that the old pass works on textual IR, so the bitcode repr has to be optimised by LLVM whilst as bitcode, then converted to text, optimisations run on this text and then materialised back to bitcode?

**Review by stuartarchibald — COMMENTED** [review]
Thanks for the fixes, a typo and a query else looks good.

File: docs/source/developer/numba-runtime.rst (hunk 4 above)
Comment (sklam) [reply docs/source/developer/numba-runtime.rst:83]: Yes. I agree it wasn't written clearly. I didn't actually change it though, just shuffled the line-breaks around to fit.

File: docs/source/developer/numba-runtime.rst [hunk 5]
```diff
@@ -48,21 +48,39 @@ Optimizations
...
-operations.
+on an optimization pass to remove redundant reference count operations.
 
-The optimization pass runs on block level to avoid control flow analysis.
+A new optimization pass is implemented in version 0.52.0 to remove reference
+count operations that fall into the following four categories of control-flow
+structure---per basic-block, diamond, fanout, fanout+raise. See the documentation
+for :envvar:`NUMBA_LLVM_REFPRUNE_FLAGS` for their descriptions.
+
+The old optimization pass runs on block level to avoid control flow analysis.
```
Comment (stuartarchibald) [inline docs/source/developer/numba-runtime.rst:58]:
```suggestion
The old optimization pass runs at block level to avoid control flow analysis.
```

File: docs/source/developer/numba-runtime.rst [hunk 6]
```diff
@@ -48,21 +48,39 @@ Optimizations
...
+callee in a LLVM call instruction.
+
+To summarize, all functions exposed to the refcount optimization pass
+**must not** consume counted references unless done so via ``NRT_decref``.
 
 
-Quirks
-------
+Quirks of legacy optimization pass
+----------------------------------
```
Comment (stuartarchibald) [inline docs/source/developer/numba-runtime.rst:78]:
```suggestion
Quirks of old optimization pass
-------------------------------
```
Apologies, I made this needlessly confusing, we should use "legacy" or "old" but not both, as "old" is prevalent throughout let's use that.

File: docs/source/developer/numba-runtime.rst [hunk 7]
```diff
@@ -48,21 +48,39 @@ Optimizations
...
 
-Since the `refcount optimization pass <nrt-refct-opt-pass_>`_ requires LLVM
-function optimization pass, the pass works on the LLVM IR as text.  The
-optimized IR is then materialized again as a new LLVM in-memory bitcode object.
+Since the pre-0.52.0 `refcount optimization pass <nrt-refct-opt-pass_>`_
+requires LLVM function optimization pass, the pass works on the LLVM IR as
```
Comment (stuartarchibald) [inline docs/source/developer/numba-runtime.rst:81]:
```suggestion
requires the LLVM function optimization pass, the pass works on the LLVM IR as
```

File: docs/source/developer/numba-runtime.rst (hunk 4 above)
Comment (stuartarchibald) [reply docs/source/developer/numba-runtime.rst:83]: I agree on the basis that only core developers adjusted it and it's being retired. Apart from adding the missing "the" above, let's just leave it.

**Review by stuartarchibald — COMMENTED** [review]
Few typos else looks good, thanks for the fixes.

File: docs/source/developer/numba-runtime.rst [hunk 8]
```diff
@@ -48,21 +48,39 @@ Optimizations
...
+callee in a LLVM call instruction.
+
+To summarize, all functions exposed to the refcount optimization pass
+**must not** consume counted references unless done so via ``NRT_decref``.
 
 
-Quirks
-------
+Quirks of old optimization pass
+-------------------------------
```
Comment (stuartarchibald) [inline docs/source/developer/numba-runtime.rst:78]:
```suggestion
Quirks of the old optimization pass
-----------------------------------
```

**Comment by stuartarchibald** [comment]
13b9569 fixes a typo.

**Comment by stuartarchibald** [comment]
Assuming CI passes this is good to go, thanks for fixing this!

**Review by stuartarchibald — APPROVED** [review]
