### PR TITLE
Solve memory leak to fix issue #7210 

### LINKED ISSUE #7210: Memory leak bugs in module init functions with PyObject_SetAttrString
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**(a static analyzer bug report)**

In file `numba/np/ufunc/omppool.cpp`, `numba/np/ufunc/tbbpool.cpp`, `numba/np/ufunc/_num_threads.c`, and `numba/np/ufunc/workqueue.c`, function `PyObject_SetAttrString` is used to add functions to the module being imported in the way shown below.

```c
PyObject_SetAttrString(m, "function_name", PyLong_FromVoidPtr(&function));
```

As the function `PyLong_FromVoidPtr` returns a new reference, it will lead to a memory leak for the `long` objects returned by `PyLong_FromVoidPtr`.

### PR DESCRIPTION
**Pull request by ysheffer**
Added a macro to _pymodule.h and set attributes in _num_threads.c, _omppool.cpp,
tbbpool.cpp, workqueue.c using a temporary variable to solve memory leak and fix #7210 .

### CODE REVIEW

**Comment by esc** [comment]
@ysheffer thank you for submitting this to the Numba issue tracker. It seems like your PR is doing a lot of cosmetics to the code in addition to implementing the feature. Do you think you could submit this PR with only the feature and not the cosmetics, as this makes it harder to review. Thanks!

**Comment by ysheffer** [comment]
@esc Thank you for your comment. Sure thing, I have updated the PR accordinaglly.

**Comment by esc** [comment]
@ysheffer thank you for making those changes, I have added it to the queue for review.

File: numba/_pymodule.h [hunk 1]
```diff
@@ -24,5 +24,10 @@
 #define PyInt_Type PyLong_Type
 #define PyInt_Check PyLong_Check
 #define PyInt_CheckExact PyLong_CheckExact
+// Define object attribute using a temporary variable to avoid memory leak
+#define SetAttrStringFromVoidPointer(m, name, tmp) \
```
Comment (Snape3058) [inline numba/_pymodule.h:28]: I think you had better wrap these three lines with a `do { } while (false)` block and declare a temporary variable in the block instead of using an external variable.

File: numba/_pymodule.h [hunk 2]
```diff
@@ -24,5 +24,10 @@
 #define PyInt_Type PyLong_Type
 #define PyInt_Check PyLong_Check
 #define PyInt_CheckExact PyLong_CheckExact
+// Define object attribute using a temporary variable to avoid memory leak
```
Comment (stuartarchibald) [inline numba/_pymodule.h:27]:
```suggestion
```
Probably don't need this.

**Review by stuartarchibald — COMMENTED** [review]
@ysheffer Many thanks for the patch, couple of minor things to look at else looks good.

File: numba/_pymodule.h (hunk 1 above)
Comment (gmarkall) [reply numba/_pymodule.h]: This is now applied, but I used `while (0)` instead of `while (false)` because `false` is not defined everywhere the macro is used.

File: numba/np/ufunc/omppool.cpp [hunk 3]
```diff
@@ -239,31 +239,24 @@ static void ready(void)
...
-                           PyLong_FromVoidPtr((void*)&do_scheduling_unsigned));
-    PyObject_SetAttrString(m, "openmp_vendor",
-                           PyString_FromString(_OMP_VENDOR));
-    PyObject_SetAttrString(m, "set_num_threads",
-                           PyLong_FromVoidPtr((void*)&set_num_threads));
-    PyObject_SetAttrString(m, "get_num_threads",
-                           PyLong_FromVoidPtr((void*)&get_num_threads));
-    PyObject_SetAttrString(m, "get_thread_id",
-                           PyLong_FromVoidPtr((void*)&get_thread_id));
+    SetAttrStringFromVoidPointer(m,launch_threads,tmp)
```
[the remark this answers is not in the document]
Comment (gmarkall) [reply numba/np/ufunc/omppool.cpp]: Comma-consistency has now been achieved.

**Comment by gmarkall** [comment]
@stuartarchibald This should be ready for another look now.

**Review by stuartarchibald — APPROVED** [review]
@ysheffer Many thanks for the patch, @gmarkall many thanks for responding to comments and providing fixes against the original patch. Good to see this leak patched.

**Comment by stuartarchibald** [comment]
@ysheffer Congratulations on your first contribution to Numba!
